### get token(login)
POST http://localhost:3000/rails_jwt_admin/authentication
content-type: application/json

{ "username":"admin", "password": "123123"}

### get me
GET http://localhost:3000/rails_jwt_admin/me
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxfQ.usIb4_TkXGDommzaBiE6rFjMmvEJmxv5wmt45MqKc9E
